kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: node:13
    commands:
      - yarn install

  - name: eslint
    image: node:13
    commands:
      - make eslint

  - name: ls-lint
    image: node:13
    commands:
      - make ls-lint

  - name: npm
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      access: public
    when:
      branch: master
      event: push

