kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: node:18
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      - make install

  - name: eslint
    image: node:18
    commands:
      - make eslint

  - name: ls-lint
    image: node:18
    commands:
      - make ls-lint

  - name: npm
    image: plugins/npm
    settings:
      username: loeffel-io
      token:
        from_secret: NPM_TOKEN
      email: lucas@loeffel.io
      access: public
    when:
      event: tag

