kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: node:16
    commands:
      - yarn install

  - name: eslint
    image: node:16
    commands:
      - make eslint

  - name: ls-lint
    image: node:16
    commands:
      - make ls-lint

  - name: codeql
    image: mcr.microsoft.com/cstsectools/codeql-container
    commands:
      - apt-get install nodejs -y
      - mkdir -p /opt/results
      - codeql database create --language=javascript /opt/results/source_db -s .
      - codeql database upgrade /opt/results/source_db
      - codeql database analyze /opt/results/source_db --format=sarif-latest --output=/opt/results/issues.sarif javascript-security-and-quality.qls
    when:
      branch: master
      event: push

  - name: npm
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      access: public
    when:
      branch: master
      event: push

